routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

Route::view('/', 'welcome');
Route::get('/help', 'Guest\HelpController@index');

Auth::routes(['register' => false]);

// Dashboard
Route::get('/home', 'HomeController@index');
Route::get('lists', 'ListController@index');

Route::group(['middleware' => 'auth', 'namespace' => 'Seller'], function () {
    //tickets
    Route::group(['prefix' => 'tickets'], function () {
        Route::get('create', 'TicketController@create');
        Route::post('create', 'TicketController@store');
        Route::get('{id}/delete', 'TicketController@delete');
    });
    //winners
    Route::get('winners', 'WinnerController@index');
});
Route::group(['middleware' => ['auth', 'admin'], 'namespace' => 'Admin'], function () {
    Route::group(['prefix' => 'admin/pages'], function () {
        Route::get('help', 'PageController@edit');
        Route::patch('help', 'PageController@update');
    });
    // users
    Route::group(['prefix' => 'users'], function () {
        Route::get('', 'UserController@index');
        Route::get('create', 'UserController@create');
        Route::post('create', 'UserController@store');
        Route::get('{id}/edit', 'UserController@edit');
        Route::post('{id}/edit', 'UserController@update');
        Route::get('{id}/deactivate', 'UserController@deactivate');
        Route::get('{id}/activate', 'UserController@activate');
        Route::get('{id}/balance', 'UserController@showBalance');
    });
    // lotteries
    Route::group(['prefix' => 'lotteries'], function () {
        Route::get('', 'LotteryController@index');
        Route::get('create', 'LotteryController@create');
        Route::post('create', 'LotteryController@store');
        Route::get('{id}/edit', 'LotteryController@edit');
        Route::post('{id}/edit', 'LotteryController@update');
    });
    
    // sales limit
    Route::get('sales-limit', 'SalesLimitController@index');
    Route::post('sales-limit', 'SalesLimitController@update');
    
    // raffles
    Route::group(['prefix' => 'raffles'], function () {
        Route::get('create', 'RaffleController@create');
        Route::post('create', 'RaffleController@store');
        Route::get('{id}', 'RaffleController@show');
    });
});

Route::get('raffles', 'Admin\RaffleController@index');

Route::group(['middleware' => 'auth', 'namespace' => 'Report'], function () {
    //reports
    Route::group(['prefix' => 'report'], function () {
        Route::get('sales', 'SaleController@index');
    });
    //balance sheets
    Route::get('balance_sheets', 'BalanceSheetController@index');
});

// Dashboard links
//Route::get('/users', 'UserController@index');
//Route::get('/user/{id}/lists', 'UserController@lists');
Route::get('/dates', 'DateController@index');

// Sent list routes
Route::get('/ticket/{id}', 'TicketController@show');
Route::get('/ticket/{id}/excel', 'TicketController@excel');
Route::get('/ticket/{id}/pdf', 'TicketController@pdf');

app/Ticket.php
<?php

namespace App;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Ticket extends Model
{
    use softDeletes;

    protected $casts = [
        'created_at' => 'datetime:Y-m-d H:i:s',
    ];

    protected $appends = [
        'lotteries_list'
    ];

    public function user()
    {
        return $this->belongsTo(User::class, 'user_id')->withTrashed();
    }

    public function plays()
    {
        return $this->hasMany(TicketPlay::class, 'ticket_id');
    }

    public function group_plays()
    {
        return $this->plays()
            ->select('lottery_id', 'type', 'point')
            ->groupBy('lottery_id', 'type', 'point');
    }

    public function lotteries()
    {
        return $this
            ->belongsToMany(Lottery::class, 'ticket_lottery', 'ticket_id', 'lottery_id');
    }

    public function getWinnerNumbersAttribute()
    {
        $ticketPlayIds = $this->plays()
            ->pluck('id')
            ->toArray();

        $winnerIds =  Winner::whereIn('ticket_play_id', $ticketPlayIds)
            ->distinct('ticket_play_id')
            ->pluck('ticket_play_id')
            ->toArray();

        $ticketPlayWinnerIds = $this->plays()
            ->whereIn('id', $winnerIds)
            ->pluck('number')
            ->toArray();

        return implode(', ', $ticketPlayWinnerIds);
    }

    public function getLotteriesListAttribute()
    {
        $list = "";

        foreach ($this->lotteries as $lottery) {
            $list .=  ($lottery->abbreviated .  ' ');
        }

        return $list;
    }

    /**
     * @return string representing the total_pints of the ticket
     */
    public function getSumPointsAttribute()
    {
        return number_format($this->total_points, 2, ',', ' ');
    }

    public function getAvailableDeleteAttribute()
    {
        $max5Mins = $this->created_at > Carbon::now()->subMinutes(5);
        $isAdmin = auth()->user()->is_role(USER::ADMIN);
        $playIds = $this->plays()->pluck('id');

        $winner = Winner::whereIn('ticket_play_id', $playIds)
            ->where('user_id', $this->user_id)
            ->exists();

        return !$winner && ($isAdmin || $max5Mins);
    }

}

resources/views/includes/navbar.blade.php
<nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
    <div class="container">
        <a class="navbar-brand" href="{{ url('/') }}">
            {{ config('app.name', 'Laravel') }}
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <!-- Left Side Of Navbar -->
            <ul class="navbar-nav mr-auto">
                @if(Auth::check())
                    <li class="nav-item {{ request()->is('home') ? 'active' : '' }}">
                        <a class="nav-link" href="{{ url('home') }}">Inicio</a>
                    </li>
                    <li class="nav-item {{ request()->is('lists') ? 'active' : '' }}">
                        <a class="nav-link" href="{{ url('lists') }}">Lista</a>
                    </li>
                    @if(auth()->user()->is_role(\App\User::ADMIN))
                    <li class="nav-item {{ request()->is('lotteries*') ? 'active' : '' }}">
                        <a class="nav-link" href="{{ url('lotteries') }}">Loterías</a>
                    </li>
                    @endif
                    <li class="nav-item {{ request()->is('tickets*') ? 'active' : '' }}">
                        <a class="nav-link" href="{{ url('tickets/create') }}">Tickets</a>
                    </li>
                    <li class="nav-item {{ request()->is('*sales') ? 'active' : '' }}">
                        <a class="nav-link" href="{{ url('report/sales') }}">Ventas por rango</a>
                    </li>
                    <li class="nav-item {{ request()->is('*winners') ? 'active' : '' }}">
                        <a class="nav-link" href="{{ url('winners') }}">Números ganadores</a>
                    </li>
                    <li class="nav-item {{ request()->is('raffles*') ? 'active' : '' }}">
                        <a class="nav-link" href="{{ url('raffles') }}">Sorteos</a>
                    </li>
                    @if(auth()->user()->is_role(\App\User::ADMIN))
                        <li class="nav-item {{ request()->is('sales-limit*') ? 'active' : '' }}">
                            <a class="nav-link" href="{{ url('sales-limit') }}">Límite de ventas</a>
                        </li>
                        <li class="nav-item {{ request()->is('users*') ? 'active' : '' }}">
                            <a class="nav-link" href="{{ url('users') }}">Usuarios</a>
                        </li>
                    @endif
                    <li class="nav-item {{ request()->is('*balance_sheets') ? 'active' : '' }}">
                        <a class="nav-link" href="{{ url('balance_sheets') }}">Balance de cuenta</a>
                    </li>
                @endif
            </ul>

            <ul class="navbar-nav ml-auto">
                @guest
                    <li class="nav-item">
                        <a class="nav-link" href="{{ route('login') }}">Ingresar</a>
                    </li>
                    @if (Route::has('register'))
                        <li class="nav-item">
                            <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                        </li>
                    @endif
                @else
                    <li class="nav-item dropdown">
                        <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                            {{ Auth::user()->name }}
                        </a>

                        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                            @if (auth()->user()->is_role(1))
                                <a class="dropdown-item" href="{{ url('admin/pages/help') }}">
                                    Gestionar ayuda
                                </a>
                            @else
                                <a class="dropdown-item" href="{{ url('help') }}">
                                    Ayuda
                                </a>
                            @endif
                            <a class="dropdown-item" href="{{ route('logout') }}"
                               onclick="event.preventDefault(); document.getElementById('logout-form').submit();">
                                Salir
                            </a>
                            <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                                @csrf
                            </form>
                        </div>
                    </li>
                @endguest
            </ul>
        </div>
    </div>
</nav>

resources/views/includes/sold_tickets.blade.php
<div class="table-responsive">
    @csrf
    <table class="table table-bordered">
        <thead>
        <tr>
            <th>Nro Ticket</th>
            <th>Vendedor</th>
            <th>Loterías</th>
            <th>Fecha Compra</th>
            <th>Opciones</th>
        </tr>
        </thead>
        <tbody>
        @foreach ($tickets as $ticket)
            <tr>
                <td>{{ $ticket->code }}</td>
                <td>{{ $ticket->user->name }}</td>
                <td>
                    @foreach($ticket->lotteries as $lottery)
                        {{ $lottery->name }}{{ !$loop->last ? ', ' : '' }}
                    @endforeach
                </td>
                <td>{{ $ticket->created_at }}</td>
                <td>
                    <a href="{{ url('ticket/'.$ticket->id) }}" class="btn btn-primary btn-sm">
                        <i class="fa fa-list-ul"></i>
                        Ver detalles
                    </a>
                    @if($ticket->available_delete)
                        <button data-delete="{{ url('api/tickets/'.$ticket->id.'/delete') }}" class="btn btn-danger btn-sm">
                            <i class="fa fa-times"></i>
                            Anular
                        </button>
                    @endif
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>
</div>

{{ $tickets->links() }}